name: Run-Tests

on: push

jobs:
  run-test:
    name: running tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: uses node
        uses: actions/setup-node@v1

      - name: install dependencies
        run: npm i --prefix src

      - name: run test
        run: npm run test --prefix src